"use strict";

$( document ).ready( () => {

    $("#submit").click( () => {
       
        const firstName = $("#fname").val();
        const lastName = $("#lname").val();
        const email = $("#email").val();
        const comment = $("#comment").val();
        const phone = $("#phone").val();
        let valid = true;
        
        
        const emailPattern = /^[\w\.\-]+@[\w\.\-]+\.[a-zA-Z]+$/;
        const phonePattern = /^\d{3}-\d{3}-\d{4}$/;
        const phonePattern2 = /^(\d{10}|\d{11})$/;

//first name
        
        if (firstName == "") { 
            $("#fnamevalid").text("*Required");
            valid = false;
        }
        else{
            $("#fnamevalid").text("*");
        }
    
//last name

        if (lastName == "") { 
            $("#lnamevalid").text("*Required");
            valid = false;
        }
        else{
            $("#lnamevalid").text("*");
        }
    
//email

        if (email == ""){
            $("#emailvalid").text("*Required");
            valid = false;
        }
        else if(!emailPattern.test(email)){
            $("#emailvalid").text("*Please enter a valid email-address");
            valid = false;
        }
        else{
            $("#emailvalid").text("*");
        }

//phone number

        if (phone == "" || (!phonePattern.test(phone) && !phonePattern2.test(phone))) {
            $("#phonevalid").text("*Please enter a valid phone number in XXX-XXX-XXXX format");
            valid = false;
        }
        else{
            $("#phonevalid").text("*");
        }

//comments

        if(comment ==""){
            $("#invalid_comment").text("*Required");
            valid=false;
        }
        else{
            $("#invalid_comment").text("*");
        }
    
        // submit the form if valid
        if (valid) {
            alert("Successfully submitted, however, I will not be accepting emails generated by this form, this is simply a demonstration of proficiency with RegEx (the default HTML mailto: is a little ugly, and i plan on fixing this up to utilize PHP to send emails)");
            $("#contact").submit();
            $("#fname").val("");
            $("#lname").val("");
            $("#email").val("");
            $("#phone").val("");
            $("#comment").val("");
           
        }
    });

   
    
    $("#fname").focus();




});